### ISSUE TITLE
GigaWord.sample.PETR.xml file without parse blocks 

### ISSUE THREAD

**Issue by ZxXinZhang** [openeventdata/petrarch2#43]
How can I run a xml input file without parse block?
I tried to delete the content in <parse> of GigaWord.sample.PETR.xml, and run it. But failed.
From ReadMe, it says the <parse> block is optional. 
Why I cannot run it without parse block?

What is the right way to use petrarch2 to run plain text?

Thanks!!!!!

**Comment by johnb30** [comment]
As seen in this section of the README: https://github.com/openeventdata/petrarch2/blob/master/README.md#installing under the heading **StanfordNLP**, PETRARCH2 no longer supports direct integration with CoreNLP, which means that raw text input is no longer supported.

**Comment by ZxXinZhang** [comment]
Hi John,

Thank you very much!

So I have to parse raw text using StanfordNLP or Hypnos first? Then add the parsed content into <Parse> block?

Hope you had a good holiday!

Best,
Xin

**Comment by ahalterman** [comment]
The easiest way to go from text to event data is to use the full pipeline. There are step-by-step instructions here: https://andrewhalterman.com/2017/05/08/making-event-data-from-scratch-a-step-by-step-guide/

I don't think any of us have used the XML-based method in years so I'm not sure what would happen.

**Comment by ZxXinZhang** [comment]
Hi Andy,

Thanks for your sweet answer!

I just have one more question. The full pipeline solution seems perfect for scraping the content from webpages. What if my raw data is plain text? Can I figure out someway to process my raw data into desirable format in Mongo Database system?

Best,
Xin

**Comment by philip-schrodt** [comment]
The XML method definitely still works -- I used it on about 25-million stories about a year ago (okay, so at least it still worked a year ago, but I don't think there have been any changes that would break it since then). However, unlike the pipeline, you need a customized program that will convert from your input format (in my case, it was the NewsML standard) to the XML standard.

**Comment by ZxXinZhang** [comment]
Hi Philip,

Thank you.

I tried to convert my content into XML format. What I did is that I run my text using StanfordNLP first and I put the Stanford parsed text into <Parse> blocks in XML file.  But it seemed there are few events generated. A paragraph generated 0 event. But sometimes it works for another sentence, though it is rare. So I am just want to know how did you do that? With <Parse> block or leave it empty?
 
Best,
Xin

**Comment by philip-schrodt** [comment]
If you are getting any events, then you've got things formatted correctly, and definitely keep the <Parse> block, since that is where the program is getting the information. Usually, however, PETRARCH is used to code individual sentences, rather than paragraphs (in fact I'm not sure what it would do with a paragraph-length Stanford parse, though probably it would stop at the end of the first sentence), so you'll probably get a higher yield of events if you split the paragraphs into sentences.

The number of events generated will very much depend on the texts you are trying to code (the existing verbs dictionary is designed to primarily code events associated with political conflict situations, since that was the focus of the CAMEO ontology) and the actor dictionaries you are using. You can over-ride the actor dictionaries and have the program produce any events where it finds a verb phrase in the dictionary by setting the variable **new_actor_length** in the file _PETR_config.ini_ to a value > 0: I'd suggest something in the range 15 - 35 -- the higher the number, the more cases you will get. It is also relatively easy to add in actors to the dictionaries if you are interested in specific cases.

**Comment by ZxXinZhang** [comment]
Thank you very much!!
