### ISSUE TITLE
Function to return phrases tuple from CoreNLP input

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/petrarch2#6]
As part of our dictionary development work, we need a function that will take in a CoreNLP parsed sentence and return a list/dict/tuple of the source actor phrase, the verb phrase, and the target actor phrase. Clayton improved the functionality for this (5d724b1672410fb52788deff41ac15c264d28637), but we still need an easy function to return this. 

Example pseudocode:

```
parse = "(ROOT (S (NP (JJ German) (NNS troops)) (VP (VBD drove) (NP (NNS tanks)) (PP (IN into) (NP (NNP France)))) (. .)))"

def get_phrases(parse):
    parsed = utilities._format_parsed_str(parse)
    # ...
    return (source_actor_phrase, verb_phrase, target_actor_phrase)

get_phrases(parse)
("German troops", "drove", "France")
```

(or whatever phrases Petrarch would actually find)

I think both @PTB-OEDA's team at UT Dallas and @philip-schrodt may be working on this.

**Comment by cnnorris** [comment]
I'd imagine you want this on a per-event basis rather than a per-sentence basis? 

And in terms of the noun phrases, are you looking for a "minimally sufficient" phrase, or the full noun phrase? So just looking at these examples that all have more complex noun phrases:

```
 Troops from Germany -> Troops | Troops from Germany
 German troops from Berlin -> German troops | German troops from Berlin
 Troops in Germany led by the Commander from Asgard -> Troops | 
                       Troops in Germany | Troops in Germany led by ... | Troops led by ... 
```

Either way is doable, but I'm not sure which will be more useful for your purposes. 

As far as verbs go, we have the capability to return "drove tanks (into)" instead of just "drove," is that something you would want or is the main verb all you're looking for?

**Comment by PTB-OEDA** [comment]
We want both, so we can later do an experiment where we do sentence v.
Story context coding experiments.

Patrick

**Comment by ahalterman** [comment]
Good point on event vs. sentence, @cnnorris. Yes, this would be per-event, so the sentence would return a list of event tuples.

The question of how much to return is a hard one. This is all for the purpose of dictionary development, both automated and hand, so I'll talk though a coding example to help illustrate what I'm thinking. Considering for now just a sentence with the "verb" phrase "drove main battle tanks into", we might want this function to return something like this:

```
verb_phrases = {"phrase_list : ["drove (P into", "drove tanks (P into", "drove battle tanks (P into", "drove main battle tanks (P into"],
               "verb" : "drove",
               "direct_object" : ["tanks", "battle tanks", "main battle tanks"],
               "preposition" : "into"}
```

where the two lists include all the options as you go down the tree. In the hand coding setup, we can take that dictionary, check for verb and object synonyms, and then present all the combinations to the coder. The coder can then mark all the equivalent phrases (here, everything except "drove (P into") and then assign the right CAMEO code to all of them at once. Anything that's too specific can also be left unchecked.

Let me think a little more about the actors. I think getting the range of actor phrases would be best.

**Comment by philip-schrodt** [comment]
I've implemented this for most cases -- I don't think it works on compounds yet -- in the fork I've got on my site. The relevant code is in the routine utilities/extract_phrases() and this is controlled by PETRglobals.WriteActorText and PETRglobals.WriteEventText (which in turn can be set in the config.ini file). At present the phrases at appended to the event record. The text is taken from the original sentence (that is, capitalization patterns are preserved), with '...' added if words have been skipped and any actor or synonym tokens enclosed in <...> (e.g. <EGY> or <&CURRENCY>. Because of the way SCNLP splits out, for example, contractions and possessives, it doesn't always work but it does most of the time.

**Comment by philip-schrodt** [comment]
Re: events vs sentences, it works on a per-event basis

**Comment by ahalterman** [comment]
I'm testing your code from your fork, @philip-schrodt, and I'm not getting it to work. Am I doing something wrong? (Using the example from the existing tests:)

Self-contained example:

```
text = "A Tunisian court has jailed a Nigerian student for two years for helping young militants join an armed Islamic group in Lebanon, his lawyer said Wednesday."

parse = """( (S (S
    (NP (DT A) (NNP Tunisian) (NN court))
    (VP (AUXZ has)
    (VP (VBN jailed)
    (NP (DT a) (JJ Nigerian) (NN student))
    (PP (IN for)
    (NP (CD two) (NNS years)))
    (PP (IN for) (S
    (VP (VBG helping) (S
    (NP (JJ young) (NNS militants))
    (VP (VB join)
    (NP (NP (DT an) (JJ armed) (JJ Islamic) (NN group))
    (PP (IN in)
    (NP (NNP Lebanon)))))))))))) (, ,)
    (NP (PRP$ his) (NN lawyer))
    (VP (VBD said)
    (NP (NNP Wednesday))) (. .)))"""

parsed = utilities._format_parsed_str(parse)
ddict = {u'test123': {u'sents': {u'0': {u'content': text, u'parsed': parsed}},
                u'meta': {u'date': u'20010101'}}}
return_dict = petrarch2.do_coding(ddict,None)
utilities.extract_phrases(ddict[u'test123'][u'sents']['0'], "asdf")
```

returns

```
{(u'TUNJUD', u'NGAEDU', u'173'): [u'', u'', u'']}
```

as does replacing `ddict` with `return_dict`.

Any thoughts on what's going on?

**Comment by ahalterman** [comment]
Update from various emails:

Make sure config file includes:

```
write_actor_text = True
write_event_text = True
```

@philip-schrodt is currently working on:
1. Returning strings rather than printing them to log
2. Getting phrases from sentences that don't generate events

The second point is especially important for us because we're using these phrases for human and automated dictionary development.

**Comment by philip-schrodt** [comment]
Latest commit returns the phrases from do_coding() in the 'meta' dictionary. Still needs to be externally documented (yeah, it and most of the program) but I'm going to close this.
